import React, { useAppContext } from "../organisms/ContextWrapper";
import Image from "next/image";
import Head from "next/head";
import styles from "../../styles/template.module.css";

export default function Template({ children }: React.ReactNode) {
  const [contextState, contextDispatch] = useAppContext();
  const mainStyle = {
    color: contextState.lightMode === "light" ? "black" : "white",
    backgroundColor: contextState.lightMode === "light" ? "#FFF" : "#000",
  };

  return (
    <div className="bg-black">
      <Head>
        <title>Network Visual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-col items-center text-white py-0 pt-8 pb-16">
        {children}
      </main>

      <footer className="flex items-center pt-0 px-8 pb-4">
        <p>Powered by</p>
        <span className="h-4 ml-2">
          <Image
            src="/the_movie_db.svg"
            alt="Vercel Logo"
            width={90}
            height={35}
          />
        </span>
      </footer>
    </div>
  );
}
