import { useAppContext } from "../organisms/ContextWrapper";
import Image from "next/image";
import Head from "next/head";
import styles from "../../styles/template.module.css";

export default function Template({ children }) {
  const [contextState, contextDispatch] = useAppContext();
  const mainStyle = {
    color: contextState.lightMode === "light" ? "black" : "white",
    backgroundColor: contextState.lightMode === "light" ? "#FFF" : "#000",
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Network Visual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={mainStyle}>
        {children}
      </main>

      <footer className={styles.footer}>
        <p>Powered by</p>
        <span className={styles.logo}>
          <Image
            src="/the_movie_db.svg"
            alt="Vercel Logo"
            width={90}
            height={35}
          />
        </span>
      </footer>
    </div>
  );
}
