import { useAppContext } from "../organisms/ContextWrapper";
import Image from "next/image";
import Head from "next/head";
import clsx from "clsx";

import Header from "../organisms/Header";

export default function Template({ children, ...props }: React.ReactNode) {
  const [contextState, contextDispatch] = useAppContext();

  return (
    <div
      className={clsx(
        contextState.lightMode === "light"
          ? "bg-black text-white"
          : "bg-white text-black"
      )}
    >
    <Head>
        <title>Network Visual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-col items-center py-2">
        <Header {...props} />
        <div className="w-screen py-0 px-3 transition-all lg:columns-2 xs:columns-1">
          {children}
        </div>
      </main>

      <footer className="flex-1 items-center pt-0 px-8 pb-4 border-t-[.1px] border-black-200">
        <p>Powered by</p>
        <span className="h-4 ml-2">
          <Image
            src="/the_movie_db.svg"
            alt="Vercel Logo"
            width={90}
            height={35}
          />
        </span>
      </footer>
    </div>
  );
}
