import { useAppContext } from "../organisms/ContextWrapper";
import Image from "next/image";
import Head from "next/head";
import clsx from "clsx";

import Header from "../organisms/Header";

export default function MainContainer({
  children,
  lgColumns,
  ...props
}: React.ReactNode) {
  const [contextState, contextDispatch] = useAppContext();

  return (
    <div
      className={clsx(
        "min-h-screen flex flex-col justify-between",
        contextState.lightMode === "light"
          ? "bg-black text-white"
          : "bg-white text-black"
      )}
    >
      <Head>
        <title>Network Visual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header {...props} />
      <main
        className={`flex flex-col items-center py-2 w-screen py-0 px-3 transition-all lg:columns-${lgColumns} xs:columns-1`}
      >
        {children}
      </main>

      <footer className="border-t-[.5px] border-black-200">
        <div className="flex py-2 px-2">
          <span className="mr-2">Powered by: </span>
          <Image
            src="/the_movie_db.svg"
            alt="Vercel Logo"
            width={90}
            height={35}
          />
        </div>
      </footer>
    </div>
  );
}
