import { useAppContext } from "../organisms/ContextWrapper";
import Image from "next/image";
import Head from "next/head";

export default function Template({ children }: React.ReactNode) {
  const [contextState, contextDispatch] = useAppContext();
  const conditionalStyle =
    contextState.lightMode === "light"
      ? "bg-black text-white"
      : "bg-white text-black";

  const defaultStyle =
    "min-h-screen flex flex-col items-center py-0 pt-8 pb-1 ";

  console.log(defaultStyle + conditionalStyle);
  return (
    <div className={conditionalStyle}>
      <Head>
        <title>Network Visual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={defaultStyle}>{children}</main>

      <footer className="flex-1 items-center pt-0 px-8 pb-4 border-t-[.1px] border-black-200">
        <p>Powered by</p>
        <span className="h-4 ml-2">
          <Image
            src="/the_movie_db.svg"
            alt="Vercel Logo"
            width={90}
            height={35}
          />
        </span>
      </footer>
    </div>
  );
}
